apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/flask-app
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kustomize:
    paths: 
      - config
portForward:
  - resourceType: service
    resourceName: flask-app-svc
    namespace: default
    port: 80
    localPort: 8080
profiles:
  - name: remote-build
    build:
      googleCloudBuild: {}
  - name: prod
    deploy:
      kustomize:
        paths:
        - https://github.com/agmsb/blueprints/team-seven/overlays/prod