apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/flask-app
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kustomize:
    paths: 
      - config
portForward:
  - resourceType: service
    resourceName: flask-app-svc
    namespace: default
    port: 80
    localPort: 8080